# Variables
$browser = zen-browser

# Keybinds
bindd = $mainMod, B, Opens your preferred browser ($browser), exec, $browser

bind = $mainMod, P, exec, hyprctl keyword general:layout "$(hyprctl getoption general:layout | grep -q 'dwindle' && echo 'master' || echo 'dwindle')" #! @description: "Toggle between dwindle and master layout"; @windows;
bind = $mainMod, M, layoutmsg, swapwithmaster master
bind = $mainMod SHIFT, tab, exec, ~/.local/bin/toggle-audio.sh


windowrulev2 = float,initialClass:^(steam)$,initialTitle:^(?!.*Steam).*$



exec-once = proton-pass &